### ISSUE TITLE
redocly bundle with a reference to a JSON schema root object produces invalid OpenAPI spec

### ISSUE THREAD

**Issue by sareykaj** [Redocly/redocly-cli#1613] opened 2024-07-07 10:41 UTC
I have a type definition in JSON schema:

> types/simple.yaml

```
$id: simple.yaml
$schema: https://json-schema.org/draft/2020-12/schema
title: SimpleType
description: My simple type
type: object
properties:
  simple_entry:
    type: string
  reference_entry:
    $ref: '#/$defs/ref_entry'
  obj_entry:
    $ref: '#/$defs/object_entry'
required:
  - simple_entry
  - reference_entry

$defs:
  ref_entry:
    type: string

  object_entry:
    type: object
    properties:
      hip:
        type: string
      hop:
        $ref: '#/$defs/another_entry'

  another_entry:
    type: string
```
and an OpenAPI 3.1 spec that references the root level type:
```
openapi: '3.1.0'
info:
  title: Example
  version: '0.0.1'
servers:
  - url: /none

paths:
  /example:
    get:
      operationId: example
      responses:
        '200':
          description: Example response.
          content:
            application/json:
              schema:
                $ref: 'types/simple.yaml'
```
Then the bundle result (`redocly bundle`) is:
```
openapi: 3.1.0
info:
  title: Example
  version: 0.0.1
servers:
  - url: /none
paths:
  /example:
    get:
      operationId: example
      responses:
        '200':
          description: Example response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/simple'
components:
  schemas:
    another_entry:
      type: string
    ref_entry:
      type: string
    object_entry:
      type: object
      properties:
        hip:
          type: string
        hop:
          $ref: '#/components/schemas/another_entry'
    simple:
      $id: simple.yaml
      $schema: https://json-schema.org/draft/2020-12/schema
      title: SimpleType
      description: My simple type
      type: object
      properties:
        simple_entry:
          type: string
        reference_entry:
          $ref: '#/components/schemas/ref_entry'
        obj_entry:
          $ref: '#/components/schemas/object_entry'
      required:
        - simple_entry
        - reference_entry
      $defs:
        ref_entry:
          type: string
        object_entry:
          type: object
          properties:
            hip:
              type: string
            hop:
              $ref: '#/components/schemas/another_entry'
        another_entry:
          type: string
```

The resulting OpenApi spec is invalid, as $id, $schema, and the whole $defs object are copied over to the `simple` object definition.
I would have expected that these are removed.

When I reference an object defined within the $defs section:
```
openapi: '3.1.0'
info:
  title: Example
  version: '0.0.1'
servers:
  - url: /none

paths:
  /example:
    get:
      operationId: example
      responses:
        '200':
          description: Example response.
          content:
            application/json:
              schema:
                $ref: 'types/simple.yaml#/$defs/object_entry'
```
... then the output is valid:
```
openapi: 3.1.0
info:
  title: Example
  version: 0.0.1
servers:
  - url: /none
paths:
  /example:
    get:
      operationId: example
      responses:
        '200':
          description: Example response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/object_entry'
components:
  schemas:
    another_entry:
      type: string
    object_entry:
      type: object
      properties:
        hip:
          type: string
        hop:
          $ref: '#/components/schemas/another_entry'

```

**Redocly Version(s)**

@redocly/cli@1.17.1

**`Node.js` Version(s)**

node 16.14.0

**Comment by sareykaj** [comment] 2024-07-08 16:10
OK, when I read this here: https://json-schema.org/blog/posts/bundling-json-schema-compound-documents then it seems to be correctly bundled and my OpneAPI editor did not like the result. Though having the $defs included inline looks strange to me.

**Comment by tatomyr** [comment] 2024-07-09 16:32
> having the $defs included inline looks strange to me.

They aren't necessary in this case indeed. However, this is not a bug, so I'm closing the issue. 

If you think they should be removed, consider writing a [custom decorator](https://redocly.com/docs/cli/custom-plugins/custom-decorators) for that.

**Closed by tatomyr** 2024-07-09 16:32 UTC
Labels: Type: Bug
