### ISSUE TITLE
Header component improperly flagged as not meeting spec

### ISSUE THREAD

**Issue by atzawada** [Redocly/redocly-cli#611] opened 2022-03-30 04:11 UTC
**Describe the bug**
When defining a common header in an OASv3 doc, the CLI flags both the `name` and `in` field as required when they are not allowed in the spec, per https://swagger.io/specification/#header-object

**To Reproduce**
* Add the following to an OASv3 doc:
```yaml
components:
  headers:
    X-Application-Msg-ID:
      description: An optional message ID that can be used to debug calls to the API
      schema:
        type: string
```
* lint using the CLI

The header object will be flagged by the `spec` rule for not having the `name` and `in` fields.

**Expected behavior**
These fields should not be flagged as they are not permitted in the OASv3 schema.

**`openapi-cli` Version(s)**
`1.0.0-beta.91`

**`Node.js` Version(s)**
`v16.13.1`

**Comment by tatomyr** [comment] 2022-03-30 18:21
Hi @atzawada, 
Could the issue be caused by some other configuration or a specific content of your definition file? I cannot reproduce it from your example.

**Comment by jeremyfiel** [comment] 2022-06-28 19:08
if you are using the component>headers in the Parameters map, this will throw an error by the linter as it's expecting a Parameter Object.  The `Operation Object` does not have a provision for a `headers` collection

https://spec.openapis.org/oas/v3.0.3#operation-object

something like this..

```yaml
paths:
   /some-path:
     get: 
       parameters:
         - $ref: '#/components/headers/X-Application-Msg-ID'
```

the proper way to use the components>headers is in the `Response Object`.

https://spec.openapis.org/oas/v3.0.3#response-object

```yaml
paths:
   /some-path:
     get: 
       parameters:
         - $ref: '#/components/parameters/some-query-parameter'
       responses:
       200:
         description: i love OpenAPI
         headers:
           -  $ref: '#/components/headers/X-Application-Msg-ID'
         content:
            application/json:
              schema:
                type: string
```

**Comment by RomanHotsiy** [comment] 2022-06-28 21:10
Thanks, @jeremyfiel!

@atzawada so you can't reuse the Header object in parameters.

We'll add some better error messages for this case later. I'll close this issue for now.

Meanwhile, you can upvote @jeremyfiel's suggestion on OpenAPI spec repo: https://github.com/OAI/OpenAPI-Specification/discussions/2930#discussioncomment-2785142

**Closed by RomanHotsiy** 2022-06-28 21:10 UTC
Labels: question
