### ISSUE TITLE
AsyncAPI 3.0.0 support

### ISSUE THREAD

**Issue by kiriakos** [Redocly/redocly-cli#1431] opened 2024-02-13 06:43 UTC
**Is your feature request related to a problem? Please describe.**

The AsyncAPI initiative released v3.0.0 of their specification at the beginning of December. Teams have started migrating but linting support is missing. Are there plans for adding linting support to redocly-cli for the new version?

**Describe alternatives you've considered**

No alternatives considered right now but might be open to forking/contributing

**Additional context**

https://www.asyncapi.com/blog/release-notes-3.0.0

**Comment by lornajane** [comment] 2024-02-13 09:01
We have it open as an issue in #1352 to see if there's any interest or engagement, it's not prioritised on our side and there's quite a few features ahead of it since we don't (yet!) see a huge amount of AsyncAPI adoption. We'd definitely be open to reviewing a contribution though!

**Comment by lornajane** [comment] 2024-02-23 13:47
I'm going to close this since it's a duplicate of #1352 - but we are very open to pull requests and/or happy to hear about forks. Thanks!

**Closed by lornajane** 2024-02-23 13:47 UTC
Labels: Type: Enhancement
