### ISSUE TITLE
Some log output is falsely written to stderr

### ISSUE THREAD

**Issue by hertg** [Redocly/redocly-cli#1277] opened 2023-09-28 08:13 UTC
> [!NOTE] 
> Related: #1193 

**Describe the bug**

Some outputs that aren't actually indicating any issues are written to stderr when they should be written to stdout.

https://github.com/Redocly/redocly-cli/blob/eb827254637d3d17a30b2285fad7d37fb5a3318b/packages/cli/src/commands/build-docs/utils.ts#L63

https://github.com/Redocly/redocly-cli/blob/eb827254637d3d17a30b2285fad7d37fb5a3318b/packages/cli/src/commands/build-docs/utils.ts#L40

**To Reproduce**

*Command*
```bash
redocly build-docs openapi.yaml --output output.html > stdout.log 2> stderr.log
```

*stdout.log*
```

🎉 bundled successfully in: tmp.html (177 KiB) [⏱ 3ms]
```

*stderr.log*
```
Found redocly.yaml and using theme.openapi options
Prerendering docs
```

**Expected behavior**

Only logs indicating problems or critical warning should be printed to stderr. 

Alternatively, such outputs should either be suppressed by default and only show up when using verbose flags `-vv` or there should be a flag to manually suppress such messages with a `--silent` or `--quiet` flag.

**Redocly Version(s)**

```
$ redocly --version
1.2.0
```

**`Node.js` Version(s)**

```
$ node --version
v16.20.2
```

**Additional context**

I'm running redocly as a subtask in my sbt build process. Because I pass the redocly output to my own logger, it gets picked up the same way as actual errors would.

![image](https://github.com/Redocly/redocly-cli/assets/3533648/9fed5a94-7228-4fe3-aedd-f0605af9a8ac)

**Comment by tatomyr** [comment] 2023-09-28 09:33
Thanks for reporting!

@lornajane I remember we already discussed sorting out the stdout/stderr outputs. Here's the [corresponding issue](https://github.com/Redocly/redocly-cli/issues/1249) for the `bundle` command. Do we maybe want to consolidate all the related issues?

**Comment by lornajane** [comment] 2023-09-28 10:17
Yes, I think there's a few things going on in the different commands. Thanks @hertg for sharing this, I think it's appropriate to output additional information to stderr, and you should find that the exit codes are the best way to tell if something succeeded. That said, the option to silence non-error output is reasonable and I'm adding that to our list of features to consider.

**Comment by hertg** [comment] 2023-09-28 11:42
> @lornajane you should find that the exit codes are the best way to tell if something succeeded.

I thought about checking the exit code and only pass on the output from stderr if it was non-zero... But I can give you an example where that doesn't work: If I have an error in the `redocly.yaml `, it prints a useful error message to stderr that I definitely want to pass on, but the process exits successfully.

That's an error I got recently. Despite this error, the `build-docs` command completed with exit code 0.

*stdout*
```

🎉 bundled successfully in: tmp.html (96 KiB) [⏱ 3ms].
```

*stderr*
```
[1] :21:25 at #/theme/openapi/theme/typography/fontWeightBold

Expected type `string` but got `integer`.

19 | typography:
20 |   fontFamily: Inter,Roboto,sans-serif
21 |   fontWeightBold: 700
   |                   ^^^
22 |   headings:
23 |     fontFamily: Inter,Roboto,sans-serif

Error was generated by the configuration spec rule.


❌ Your config has 1 error.
```

---

> I think it's appropriate to output additional information to stderr,

For what reason? I can see the argument to print diagnostic information to stderr if it is "unintended" output that you don't want to print to stdout, "unintended" in the sense that the user "didn't ask for it", so you don't want to clutter stdout with diagnostics. But I'd argue that printing diagnostic information the user didn't ask for is better left behind a `verbose` flag, making the user ask for it, and then it can be printed to stdout. Of course, that comes down to personal preference, just wanted to give an alternative viewpoint. :)

**Comment by tatomyr** [comment] 2023-09-28 12:23
@hertg Oh, that's interesting. The reason it exits with 0 is that the error is in the config (and not in the API description itself), and we treat config errors separately. However, it should be a warning, not an error. For instance, the `lint` command produces a warning on the same config (again, it is not counted in the overall stats, which is expected).

**Comment by hertg** [comment] 2023-09-28 12:52
@tatomyr I have no issues with it exiting successfully when there are config errors :) My point is that because of this mix of diagnostics and warnings/errors in stderr, I'm forced to always pass on what redocly prints to stderr, because there is no way for me to know whether it contains just diagnostics or actual warnings / errors. And I obviously want to pass them on as errors to our logs, because I want actual errors to show up as such, including config errors.

Right now, I have to communicate to the developers that the redocly errors in their logs can almost always be ignored, because they're just diagnostics. But I don't really like conditioning engineers to ignore error messages :stuck_out_tongue: 

Although I'd prefer it not to print diagnostics to stderr by default, If there was an opt-in flag that I can set which has the effect that diagnostics are no longer printed to stderr, my needs would already be satisfied.

**Comment by tatomyr** [comment] 2023-09-29 12:15
@hertg I see your point, but I'm referring to the actual bug you've accidentally helped to find. 

Regarding your case, if you want to know if there are warnings/errors, you may tweak the rules' severity in a separate config and run the command against it (see [here](https://github.com/Redocly/redocly-cli/issues/747#issuecomment-1169386991)). If there are any, it will exit with 1. I understand that it won't work for config errors though. So it might be a good idea to introduce a flag or a config option that will force failing on config errors. I hope this makes sense.

**Comment by lornajane** [comment] 2023-10-02 10:52
The extra content in stderr is useful feedback for humans using the CLI at a command prompt, but you should be safely able to ignore it if there's a success response code! I agree with @tatomyr, an error from linting the configuration is still an error and should return the appropriate status code.

**Comment by sheldonreddy** [comment] 2023-10-13 16:47
I'm having the same issue.

With the following areas:

1. Bundling
2. Linting
3. Documentation
4. A new update is available

I've managed to handle the incorrect behaviour in code however my logs contain the errors. 

Within my Nuke build Errors & Warnings, you can see the compilation of these errors. This is outside of each individual step spitting out the same errors.

`[ERR] BundleOASpecificatio:     ╔══════════════════════════════════════════════════════╗
[ERR] BundleOASpecificatio:     ║                                                      ║
[ERR] BundleOASpecificatio:     ║  A new version of Redocly CLI (1.2.0) is available.  ║
[ERR] BundleOASpecificatio:     ║  Update now: `npm i -g @redocly/cli@latest`.         ║
[ERR] BundleOASpecificatio:     ║  Changelog: https://redocly.com/docs/cli/changelog/  ║
[ERR] BundleOASpecificatio:     ║                                                      ║
[ERR] BundleOASpecificatio:     ╚══════════════════════════════════════════════════════╝
[ERR] BundleOASpecificatio:   bundling C:\Dev\GitlabRepos\Hydra\DeveloperPlatform\specifications\Auth/auth-api-spec.yaml...
[ERR] BundleOASpecificatio: 📦 Created a bundle for C:\Dev\GitlabRepos\Hydra\DeveloperPlatform\specifications\Auth/auth-api-spec.yaml at C:\Dev\GitlabRepos\Hydra\DeveloperPlatform\output\specifications\auth\auth-api-spec-bundled.yaml 20ms.
[ERR] LintOASpecifications:     ╔══════════════════════════════════════════════════════╗
[ERR] LintOASpecifications:     ║                                                      ║
[ERR] LintOASpecifications:     ║  A new version of Redocly CLI (1.2.0) is available.  ║
[ERR] LintOASpecifications:     ║  Update now: `npm i -g @redocly/cli@latest`.         ║
[ERR] LintOASpecifications:     ║  Changelog: https://redocly.com/docs/cli/changelog/  ║
[ERR] LintOASpecifications:     ║                                                      ║
[ERR] LintOASpecifications:     ╚══════════════════════════════════════════════════════╝
[ERR] LintOASpecifications:   validating C:\Dev\GitlabRepos\Hydra\DeveloperPlatform\output\specifications\Auth\auth-api-spec-bundled.yaml...
[ERR] LintOASpecifications: C:\Dev\GitlabRepos\Hydra\DeveloperPlatform\output\specifications\Auth\auth-api-spec-bundled.yaml: validated in 21ms
[ERR] LintOASpecifications: Woohoo! Your OpenAPI definition is valid. 🎉
[ERR] LintOASpecifications: 2 problems are explicitly ignored.
[ERR] LintOASpecifications:
[ERR] GenerateDocumentatio:     ╔══════════════════════════════════════════════════════╗
[ERR] GenerateDocumentatio:     ║                                                      ║
[ERR] GenerateDocumentatio:     ║  A new version of Redocly CLI (1.2.0) is available.  ║
[ERR] GenerateDocumentatio:     ║  Update now: `npm i -g @redocly/cli@latest`.         ║
[ERR] GenerateDocumentatio:     ║  Changelog: https://redocly.com/docs/cli/changelog/  ║
[ERR] GenerateDocumentatio:     ║                                                      ║
[ERR] GenerateDocumentatio:     ╚══════════════════════════════════════════════════════╝
[ERR] GenerateDocumentatio:   Found undefined and using theme.openapi options
[ERR] GenerateDocumentatio: Prerendering docs
​`

**Comment by tatomyr** [comment] 2023-10-23 17:42
> If I have an error in the redocly.yaml , it prints a useful error message to stderr that I definitely want to pass on, but the process exits successfully.
That's an error I got recently. Despite this error, the build-docs command completed with exit code 0.

@hertg in Redocly CLI [v1.3.0](https://redocly.com/docs/cli/changelog/#minor-changes) (the current latest version) we've changed the default severity level for config linting to `warning` and added the `--lint-config` [option](https://redocly.com/docs/cli/commands/build-docs/#options), so you may change it to `error`. And now the CLI will exit on config errors. I hope this solves your issue at least partially.

**Comment by tatomyr** [comment] 2023-10-23 18:12
@sheldonreddy the current behaviour (outputting additional details to stderr) is designed specifically and likely will not be changed in the near term. Please describe your use case so we can better understand your need in the stderr output.

**Comment by lornajane** [comment] 2023-11-17 17:16
I think that the root cause of the original issue was corrected by the move to handle invalid configuration correctly. This means that the situation where a successful exit code is reported despite errors during processing.

We use stderr to output information about a command, to keep that diagnostic information separate from the command output. From this discussion, it seems that we should offer a way to suppress this, so I have opened #1335 as a feature request. Please check that issue meets your expectations, and feel free to follow there for updates. I'll close this issue as I think the original report was addressed.

**Closed by lornajane** 2023-11-17 17:16 UTC
Labels: Type: Enhancement
