### ISSUE TITLE
Cannot find module 'node:net'

### ISSUE THREAD

**Issue by Wayne82** [Redocly/redocly-cli#1265] opened 2023-09-16 07:07 UTC
**Describe the bug**
Running the tool gives this error "Cannot find module 'node:net'", after installing successfully.

**To Reproduce**

1. Install the tool following the instruction "npm i -g @redocly/cli@latest"
2. Installing successfully.
3. Run the command "redocly --version".
4. Then, Error: Cannot find module 'node:net'

**Expected behavior**

**Logs**

Some of the logs output from installation

> npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
> npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
> npm WARN notsup Unsupported engine for styled-components@6.0.8: wanted: {"node":">= 16"} (current: {"node":"14.15.0","npm":"6.14.8"})
> npm WARN notsup Not compatible with your version of node/npm: styled-components@6.0.8

And the error log when running "redocly --version"

> internal/modules/cjs/loader.js:883
  throw err;
  ^
>Error: Cannot find module 'node:net'
>Require stack:
> - /Users/wangwei/.nvm/versions/node/v14.15.0/lib/node_modules/@redocly/cli/node_modules/get-port-please/dist/index.cjs
> - /Users/wangwei/.nvm/versions/node/v14.15.0/lib/node_modules/@redocly/cli/lib/commands/preview-docs/preview-server/preview-server.js
> - /Users/wangwei/.nvm/versions/node/v14.15.0/lib/node_modules/@redocly/cli/lib/commands/preview-docs/index.js
> - /Users/wangwei/.nvm/versions/node/v14.15.0/lib/node_modules/@redocly/cli/lib/index.js
> - /Users/wangwei/.nvm/versions/node/v14.15.0/lib/node_modules/@redocly/cli/bin/cli.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (/Users/wangwei/.nvm/versions/node/v14.15.0/lib/node_modules/@redocly/cli/node_modules/get-port-please/dist/index.cjs:3:18)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
> 

**OpenAPI definition**

**Redocly Version(s)**

**lastest**

**`Node.js` Version(s)**
**v14.15.0**
NPM version: **6.14.8**

**Additional context**

On Mac machine Ventura 13.4.1

**Comment by tatomyr** [comment] 2023-09-16 08:45
Hi @Wayne82,  I'm not able to reproduce the issue. Could you provide any additional info? Maybe some logs output? Which NPM version you're using? Is it a fresh install our you had @redocly/cli installed before (if yes - which version it was, if you remember, of course)?

**Comment by Wayne82** [comment] 2023-09-16 09:01
Hi @tatomyr, I've update the logs, and NPM version in the description. 
It was a fresh install. 
And thanks for the help!

**Comment by tatomyr** [comment] 2023-09-16 09:12
Thanks! Looks like the issue emerges when using npm v6. 
Could you update at least to node v14.19.0+ / npm v7.24.2+? I believe this should solve your issue.

**Comment by Wayne82** [comment] 2023-09-16 09:17
👍 yes! It works now. 
Thanks @tatomyr

**Comment by tatomyr** [comment] 2023-09-21 13:48
Closing this since the minimal node/npm requirements have been updated in the docs.

**Closed by tatomyr** 2023-09-21 13:48 UTC
Labels: Type: Bug, p3
