### ISSUE TITLE
Decorators not running in build-docs but runs in docs-preview

### ISSUE THREAD

**Issue by Apoorva64** [Redocly/redocly-cli#1418] opened 2024-01-31 08:50 UTC
**Describe the bug**
I have an OpenApi with a lot of exemples.
I wrote a decorator plugin to remove all the exemples from the specification.
When i build the docs with "build-docs" the plugin does not run.
When i preview the docs with "docs-preview" the plugin runs.

**To Reproduce**

1. Given this `redocly.yaml` file
```yaml
extends:
  - recommended
plugins:
  - plugin.js
apis:
  main:
    root: openapi.yaml
    decorators:
      remove-examples/remove-examples: on

rules:
  no-empty-servers: warn
  no-invalid-media-type-examples: warn
  ```
  
2. And this OpenAPI file(s)
```yaml
openapi: 3.0.3
info:
  version: 1.1.0
  title: Pet API

security: []
 
paths:
  /pet/{petId}:
    get:
      summary: Gets the Pet from petId
      operationId: getPet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
          examples:
            DEX:
              description: Dex est un chien qui aime jouer
              value: 0
            EDDY:
              description: Eddy est un chien qui n'aime pas jouer
              value: 1
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
            
              examples:
                DEX:
                  description: Réponse 200 OK pour Dex
                  value: 
                    {
                      "id": 0,
                      "name": "Dex"
                    }
                EDDY:
                  description: Réponse 200 OK pour Eddy
                  value: 
                    {
                      "id": 1,
                      "name": "Eddy"
                    }
        "404":
          description: Pet not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Pet:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Error:
      required:
        - description
      type: object
      properties:
        description:
          type: string
```
3. And this plugin.js file which is a decorator that removes exemples
```javascript
function removeExamples() {
    return {
        any: {
            leave(target) {
                if (target.examples) {
                    target.examples = {};
                }
                if (target.example) {
                    delete target.example;
                }

            },
        },
    };
}

module.exports = {
    id: 'remove-examples',
    decorators: {
        oas3: {
            'remove-examples': removeExamples,
        },
    },
};
```
4.  `redocly build-docs main` and `redocly preview-docs main`
5. See difference between the generated doc with build-docs and the preview docs
The docs-preview has the exemples but the build-docs does not. Thus the decorators don't run in build-docs

**Expected behavior**
The plugin should run in both cases

**Redocly Version(s)**

1.8.1

**`Node.js` Version(s)**

18.17.1

**Comment by tatomyr** [comment] 2024-01-31 14:31
Hi @Apoorva64! 

That's because decorators are supposed only to run when bundling, and the `preview-docs` command happens to bundle before it runs, while the `build-docs` doesn't do this step. If you want your decorators to be applied, please use a chain of commands like this:

```bash
redocly bundle main -o openapi.bundled.yaml && redocly build-docs opepnapi.bundled.yaml
```

This isn't a bug though, but rather an unexpected behaviour. Maybe we could somehow clarify that in the docs? cc @lornajane

**Comment by Apoorva64** [comment] 2024-01-31 15:01
Hi @tatomyr,
The redocly.yaml also contains the configuration for build-docs such as theme(styling, functional options), so when we bundle it we lose that configuration.
How could we do this with a chain of commands without duplicating configuration?

Having a flag to run decorators would greatly simply this.

**Comment by lornajane** [comment] 2024-01-31 16:27
My recommendation is to bundle and apply the decorators to get the OpenAPI version that should be rendered as documentation, and then build the docs from that file whether you are previewing or building the docs. Rather than duplicating the config, move the docs-related configuration to the section for the bundled file.

Let me know if an example would be helpful?

**Comment by Apoorva64** [comment] 2024-02-02 07:51
Hi @lornajane, i understand how i need to do it to make it work. But there's something that doesn't sit right with me.
When an OpenAPI specification with multiple files is used, `redocly build-docs multi-part-openapi.yaml`, Redocly performs some sort of bundling, but it is not the same as the bundling done by the redocly bundle command as it does not run the decorators.

**Comment by lornajane** [comment] 2024-02-13 13:53
Decorators are part of the `redocly bundle` command. We do also do a simple bundle step for the docs build, but you're correct that they are not exactly the same thing. Try running bundle without decorators if you need the equivalent?

I'm reluctant to make disruptive changes to existing functionality, so @Apoorva64 I think as long as you got the information you needed from us, we can probably close this issue.

**Closed** 2024-02-19 07:15 UTC
Labels: question
