### ISSUE TITLE
join command with wildcard does not collect matching files

### ISSUE THREAD

**Issue by vip32** [Redocly/redocly-cli#1196] opened 2023-07-31 14:16 UTC
**Describe the bug**

When using the join command with a file wildcard the following error is always returned:

`At least 2 apis should be provided.`

**To Reproduce**

1. have a folder with several yaml files
2. run this command: `npx --yes @redocly/cli@latest join ./*.yaml -o ./OpenAPI.yaml`
4. See error: `At least 2 apis should be provided.`

**Expected behavior**

the files matching the wildcard should be used for joining. When using the following command (non wildcard) the join works correctly:

`npx --yes @redocly/cli@latest join .\Identity-OpenAPI.yaml .\Shopping-OpenAPI.yaml -o ./OpenAPI.yaml`
**success**: ./OpenAPI.yaml: join processed in 49ms

**Redocly Version(s)**
1.0.0 on win10

**`Node.js` Version(s)**
v19.9.0

**Comment by ZyzychO** [comment] 2023-07-31 17:27
Hello! 

Let us check this.

**Comment by romanpryshliak** [comment] 2023-08-02 12:09
Hi @vip32,

We've attempted to replicate this matter on both Mac and Windows machines, but unfortunately, we haven't been able to encounter the same issue.

![repro](https://github.com/Redocly/redocly-cli/assets/92374352/614ddf9a-2881-4a89-9df3-d39554f230fa)

Thus, could you please consider sharing with us a sample project that demonstrates this issue? This would enable us to conduct a more in-depth investigation from our side.

**Comment by vip32** [comment] 2023-08-02 16:42
Thanks for taking time for this, interesting it works in your sample though. I extracted the files and created a small repo with only the yaml files: https://github.com/vip32/openapi_tmp

executing `npx --yes @redocly/cli@latest join ./*.yaml -o ./OpenAPI.yaml` on it gives the error.

**Comment by tatomyr** [comment] 2023-08-07 09:34
Thanks for reporting @vip32!

I believe this is specific to Windows command line. We will check if it could be fixed a bit later. 
Meanwhile, as a workaround, you can use Git Bash.

**Comment by vip32** [comment] 2023-09-15 07:08
with docker (on windows) the result is the same
`docker run --rm -v .:/spec redocly/cli:latest join ./*.yaml -o .\OpenAPI.yaml` >> `At least 2 apis should be provided.`

**Comment by magdalipka** [comment] 2024-01-10 22:18
In Windows shells the wildcard is resolved to first match only. Fix proposed in `yargs`: https://github.com/yargs/yargs/issues/50#issuecomment-54087619 .

**Comment by dmitri-trofimov** [comment] 2024-03-05 09:57
The issues is in `miscellaneous.ts`, the `expandGlobsInEntrypoints` function. The `glob` does not have `__promisify__` function. To fix this you can pretty much do this:

```JavaScript
return glob.hasMagic(aliasOrPath) && !isAbsoluteUrl(aliasOrPath)
    ? (await require("util").promisify(glob)(aliasOrPath)).map((g: string) => getAliasOrPath(config, g))
    : getAliasOrPath(config, aliasOrPath);
```

Or just use the newer `glob`.

Do you want me to create a PR for this?

**Comment by dmitri-trofimov** [comment] 2024-03-10 20:26
> In Windows shells the wildcard is resolved to first match only. Fix proposed in `yargs`: [yargs/yargs#50 (comment)](https://github.com/yargs/yargs/issues/50#issuecomment-54087619) .

That's not entirely accurate. In Windows the wildcards are not resolved by the system when passed as part of an argument. Instead commands or apps resolve wildcards themselves (in case of Node.js application they usually use `glob`). In Linux, however, the system tries to resolve wildcards in command line and converts a single string with wildcards into a list of space separated existing paths that match the wildcard.

The `redocly-cli` attempts to handle it correctly, but it relies on `glob` object to have `__promisify__` function, which is missing. For some dumb reason the `__promisify__` function is present in `@types/glob` but is actually missing from the `glob` itself.

I will try to create a PR to fix this when I have the time this week. My Windows build isn't working because if this, and I am stuck with Ubuntu WSL, which I am not particularly fond of :D

**Comment by Steven-Harris** [comment] 2024-10-03 17:49
> Meanwhile, as a workaround, you can use Git Bash.

When Git Bash is not a viable option, PowerShell will work, too, as a workaround.
```
npx --yes @redocly/cli@latest join (Get-ChildItem -Filter *.yaml) -o ./OpenAPI.yaml
```

**Comment by NeelChotai** [comment] 2024-10-09 22:28
This also fails in `/bin/sh` context.

@romanpryshliak I believe that this works for you because the `./*.yaml` operator was being expanded by bash and not redocly.

The issue is actually in the section:
```ts
  if (argv.apis.length < 2) {
    return exitWithError(`At least 2 apis should be provided.`);
  }
```

The user is passing in a glob so it will always fail at this step if it's not expanded by their shell.

**Closed** 2024-12-06 18:03 UTC
Labels: Type: Bug, p3
